### ISSUE TITLE
Operators Task

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#1]
int a = 10;
int x = 0, y = 0;

x = a++;
printf("%d %d", x, a);

/* Write value of a and x below /
a =
x =
/ Write value of a and x above */

y = --a;
printf("%d %d", y, a);

/* Write value of a and y below /
a =
x =
/ Write value of a and y above */

//Write explanation for the output from your understanding below:

**Comment by prachigithubsharma** [comment]
10 11
a=11
x=10
//x=10 because the value of 'a' is considered first and then incremented as it is post increment.
10 10
a=10
y=10
//y=10 because the value of 'a' is decremented as it is pre decrement.

**Comment by giripras** [comment]
Good!!
