### ISSUE TITLE
Loop exercise

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#10]
1. Write a program to print the digits of a number(int) . Use scanf to retrieve the number. Also, print the count of digits present in that number.

2. Write a program to print the following star pattern:
    PFA, the pattern in the file attached.
[Star_pattern.txt](https://github.com/hari-eur/Prachi-Sharma---Giriprasad/files/10933387/Star_pattern.txt)
  
3. int main()
    {
        int x = 0;
        do{
              printf("%d",x);
        }while( x++ )

/*Provide the output of the following program with explanation below*/

/*Provide the output of the following program with explanation above*/

**Comment by prachigithubsharma** [comment]
1)
#include <stdio.h>

int main()
{
    int n,rem,sum=0,i;
    printf("enter the number:");
    scanf("%d",&n);
    while(n>0)
    {
        rem=n%10;
        sum=sum+rem;
        i=i+1;
        n=n/10;
    }
    printf("sum of digits=%d\n",sum);
    printf("number of digits=%d\n",i);
    return 0;
}
2)
#include <stdio.h>

int main()
{
    int i,j;
    for(j=1;j<=5;j++)
    {
        for(i=5;i>=j;i--)
        {
            printf("*");
        }
        printf("\n");
    }
    return 0;
}
3)
0 //only 0 will be printed as it is post increment and also since it is do while loop it will execute first and then checks the condition

**Comment by giripras** [comment]
1) expected output only to print the digits of the number not the sum. please re-check.
    count is correct.
   
2)Good!!
3)there's a catch. Not the expected output is present.

**Comment by prachigithubsharma** [comment]
1)
#include<stdio.h>
#include<math.h>
int main()
{
    int n,temp,count=0,p;
    printf("Enter the number:");
    scanf("%d\n",&n);
    temp=n;
    while(temp!=0)
    {
        count++;
        temp=temp/10;
    }
    p=pow(10,count-1);
    while(p!=0)
    {
        printf("%d\n",n/p);
        n=n%p;
        p=p/10;
    }
    return 0;
}
2) i have answered it in above comment
3)error //since there in no semicolon after while
