### ISSUE TITLE
Operators Continuation

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#2]
char *a = NULL;

a = ('A' > 'a')? "Hi":"Hello";
printf("%s", a);

/* Write the output below /
a =
/ Write the output above */

//Please provide explanation from your understanding.

**Comment by prachigithubsharma** [comment]
Hello
//since the ascii value of 'A' is smaller than 'a' so the condition is false and therefore Hello is printed. And if the condition was true Hi would have been printed.

**Comment by giripras** [comment]
Good!!
