### ISSUE TITLE
Order Of Evaluation

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#3]
1)

int a = 1, b = 5, c = 10, d = 0;

 d = a/b*c-a*b+c;

 printf("%d\n", d);
 
/* Write output of value d below with explanation*/
d= 

/*Write output of value d above with explanation*/

2)

int a = 1, b = 5, c = 10, y = 3;
 
 y += (a+b)*a-b/c+a*y*(a+y+c);
 printf("%d\n", y);

/* Write output of value y below with explanation*/
y= 

/*Write output of value d above with explanation*/

**Comment by prachigithubsharma** [comment]
5
//first multiplication takes place followed by division and addition and subtraction. 
51
//3+[6-0+3*14]

**Comment by giripras** [comment]
Great!!
