### ISSUE TITLE
Bitwise Operators and Const. Keyword

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#4]
1)
int a = -15, b = 2, c = 30, d = -20;
int x = ~a | b & c ^ ~d && 2 >> 1;
printf("%d\n", x);

/* Write the output of x with explanation of each bit operation below */
x = 

/* Write the output of x with explanation of each bit operation above */

2) 
const a = 97;
printf("%c\n", a-1);

/* Write output of a with explanation below */
a = 

/*Write output of a with explanation above */

**Comment by prachigithubsharma** [comment]
1
//1|2&30^12&&1
//1|2^12&&1
//1|14&&1
//15&&1 therefore its is 1
`
//as 96 is the ascii value of `

**Comment by giripras** [comment]
1)
Expected output is correct but the complement of -15 and -20 seems to be not expected. Could you please calculate those two alone correctly and fill here?
~a= 
~d= 

2)
I'm not able to see the character printed. Could you please provide it?
a= 

Also, consider I'm changing the value of a as follows:
const int a = 97;
int b = 10;
printf("%c\n", a-1);

a += b;
printf("%c\n", a);

Please provide the output with explanation here.

**Comment by prachigithubsharma** [comment]
~a=1
~d=12
a=`  
\\sorry by mistake it got erased
`
\\as 96 is the ascii value
k
\\107 is the ascii value of k

**Comment by prachigithubsharma** [comment]
a=`

**Comment by giripras** [comment]
1. complement of a and d still seems to be wrong.
Please re-check and if any queries, please ping.

2. Good a's output is correct.

3. Please check the use-case of const keyword and provide the output.

**Comment by prachigithubsharma** [comment]
3. a
// since const is used the value of 'a' will remain 97. And ascii value of 97=a
k
//as ascii value of 107=k

**Comment by giripras** [comment]
Good!!

Complement of a and d ?

**Comment by prachigithubsharma** [comment]
~a=14
~d=19

**Comment by giripras** [comment]
Good!! Hope you understood how to calculate the complements for both negative and positive integers.
