### ISSUE TITLE
Printf and Scanf Functions

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#5]
1)
   int s = 0;
   int m = 28;
   int val = 0;

   printf("The value of %ns and %nm %nval : ", &s, &m, &val);
   printf("%d\t%d\t%d", s, m, val);

/*Write output of the program below with explanation of what printf does here*/
s=
m= 
val= 

/*Write output of the program above with explanation of what printf does here*/

2)
int x = 10;
printf("%0*d\n",4, x);

float y = 7.963f;
printf("%7.2f\n", y);

char *ptr = "Test Program";
printf("%5.8s\n", ptr);

/*Write output of the program below with explanation*/
x=
y= 
ptr= 

/*Write output of the program above with explanation*/

3)
   char s[100];
   char s1[] ={"Hello, World!"};
  
   scanf("%[^\n]%*c", s); 
   printf("%s", s1);

   printf("\n");
   printf("%s", s);

/*Write output of the program below with explanation*/
Parse this string in scanf for s:
<Hi!!Hello(followed by Enter)>

/*Write output of the program above with explanation*/

**Comment by prachigithubsharma** [comment]
//1.
s=13
m=19
val=21
//2.
0010
7.96
Test Pro
//3.
Hello,World!

**Comment by giripras** [comment]
1) is correct but explanation needed.
2)except 7.96(need exact output), rest are correct but explanation needed.
3)Something missing. Please re-check.

**Comment by prachigithubsharma** [comment]
1) It counts the letters and spaces till %n is encountered. 
2)
0010 //as 4 digits should be printed and the starting first two is replaced by 0 as it is %0*
   7.96 //total 7 characters so it has 3 empty spaces in the beginning and 2 numbers after decimal
Test Pro //prints 8 characters including space
3)
hello //it is the input by the user which is s
Hello, World! //prints s1
hello // prints s

**Comment by giripras** [comment]
Good!!
