### ISSUE TITLE
Infinite Loops

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#6]
Write an example program which runs infinite times using the following loop constructs:
1. While
2. Do-While
3. For

**Comment by prachigithubsharma** [comment]
1)
#include <stdio.h>
int main()
{
    int i=1;
    while(i!=0)
    {
    printf("hello\t");
    i++;
    }

    return 0;
}
2)
#include <stdio.h>
int main()
{
    int i=1;
    do
    {
    printf("hello\t");
    i++;
    }
    while(1);

    return 0;
}
3)
#include <stdio.h>
int main()
{
for(;;)
{
printf("hello\t");
}
return 0;
}

**Comment by prachigithubsharma** [comment]
1)
#include <stdio.h>
int main()
{
int i=1;
while(i!=0)
{
printf("hello\t");
i++;
}
return 0;
}
2)
#include <stdio.h>
int main()
{
int i=1;
do
{
printf("hello\t");
i++;
}
while(1);
return 0;
}
3)
#include <stdio.h>
int main()
{
for(;;)
{
printf("hello\t");
}
return 0;
}

**Comment by giripras** [comment]
Good!!
