### ISSUE TITLE
If-else exercise

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#7]
In this exercise you will use nested if  statements to decide if someone can drive. Let's assume that anyone 16 or older can legally drive, but they must also own a car to drive.

If the person is not 16 or older then you should display, "Sorry, come back in n  years and be sure you own a car when you come back.", where "n" (declare and calculate) is how many years until the person turns 16 year old.

If the person is 16 or older but they do NOT own a car, then your program should display, "Sorry, you need to buy a car before you can drive!" .

If the person is 16 or older and they DO own a car, then your program should display, "Yes - you can drive!"

NOTE : Declare variables "age" and "has_car" of suitable type and use scanf to retrieve their values. I'll run against multiple inputs and test their behaviour.

**Comment by prachigithubsharma** [comment]
#include <stdio.h>
int main()
{
int age,has_car;
printf("enter the age:");
scanf("%d",&age);
if(age>=16)
{   
    printf("Do you own a car? ");
    scanf("%d",&has_car);
    if(has_car==1)
    {
        printf("\nYes-you can drive");
    }
    else
    {
        printf("Sorry you need to buy a car before you can drive");
    }
}
else
{
    age=16-age;
    printf("Sorry come back in %d years and be sure that you own a car when you come back",age);
}
return 0;
}

**Comment by giripras** [comment]
Good!!
Try to use boolean datatype for variables which can have max. 2 values only(eg: has_car will have either 0 or 1). No need to use entire int data-type

**Comment by prachigithubsharma** [comment]
ok sir!
