### ISSUE TITLE
Switch Case

### ISSUE THREAD

**Issue by giripras** [hari-eur/Prachi-Sharma---Giriprasad#8]
Assume a user-given character 'ch'. From this character, use the switch case decision maker to handle the following cases:
1. case 'A' (or) 'a' ---> print odd numbers from 1 - 100.
2. case 'B' (or) 'b' ---> print even numbers from 1 - 100.
3. case 'C' (or) 'c' ---> print characters from A - Z.
If other characters, print no valid option is pressed.

**Comment by prachigithubsharma** [comment]
#include <stdio.h>
int main()
{
    char ch;
    int j;
    printf("Enter the character:");
    scanf("%c",&ch);
    switch(ch)
    {
      case 'A':
      case 'a':
      for(int i=1;i<=100;i++)
      {
          if(i%2!=0)
          printf("%d\t",i);
      }
      break;
      case 'B':
      case 'b':
      for(int i=1;i<=100;i++)
      {
          if(i%2==0)
          printf("%d\t",i);
      }
      break;
      case 'C':
      case 'c':
      for(char i='A';i<='Z';++i)
      printf("%c\t",i);
      break;
      default:
      printf("No valid option is pressed");
      }
return 0;
}

**Comment by giripras** [comment]
Great!! j doesnt have any use-case. Avoid using variables which are not used in program.
